CLASS zcl_new_void_type DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
  PROTECTED SECTION.
    DATA ms_field TYPE usr02 ##NEEDED.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_NEW_VOID_TYPE IMPLEMENTATION.
ENDCLASS.
